"""clean migration

Revision ID: 5e5ccd4e5e73
Revises: 
Create Date: 2026-05-19 18:05:30.822459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5ccd4e5e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('exam_attempts_exam_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exams', ['subject_id'], ['id'])
        batch_op.drop_column('exam_id')
        batch_op.drop_column('last_question_id')

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('student_answers_attempt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exam_attempts', ['attempt_id'], ['id'])
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('subjects_subject_code_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('subjects_subject_code_key'), ['subject_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('subject_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_answers_attempt_id_fkey'), 'exam_attempts', ['attempt_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_question_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exam_attempts_exam_id_fkey'), 'exams', ['exam_id'], ['id'])
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
