"""fresh baseline

Revision ID: 9e39ccf032ad
Revises: 
Create Date: 2026-05-30 13:43:11.647623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e39ccf032ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_student_subject', ['student_id', 'subject'])

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['subject_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('subject_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('subject_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uix_student_subject', type_='unique')

    # ### end Alembic commands ###
