"""message

Revision ID: b424a1223446
Revises: 
Create Date: 2026-05-27 12:53:38.718434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b424a1223446'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('exams_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'])
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('questions_subject_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'exams', ['exam_id'], ['id'])
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_student_subject', ['student_id', 'subject'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('uix_student_subject', type_='unique')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('questions_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('exam_id')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exams_subject_id_fkey'), 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###
